### ISSUE TITLE
duplicate file records from site view

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#238] opened 2019-08-20 14:06 UTC
Duplicate records were created when uploading files from site view: see attachments from 133128 to 133139. The intention was to upload 3 files linked to site 5723. However, links to site were not created.

**Comment by enmust** [comment] 2019-08-21 10:49
Cannot reproduce duplicate error, closing this and opening new issue about duplicates

**Closed by enmust** 2019-08-21 10:49 UTC
Labels: Critical: level 2, bug
