### ISSUE TITLE
Object permissions for new records

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#427] opened 2020-02-02 08:52 UTC
If user creates a new record in table with object-level permissions, then API should grant change permission to that user. Additional permissions should come from:
- table-level configuration (could be put in settings file, like the list of guarded tables). For instance, all reference records should receive change permission to group reference-manager, new specimens should receive current user institution's ID etc.
- user-defined defaults. User may set a list of groups (and users?) that receive change (and view?) permission on every new insert; this would make 1, 2 or 4 lists of user/group IDs. These lists should be saved to db (auth_user.preferences field). User should see/edit these default permissions in the app's user preferences section.

**Comment by urtson** [comment] 2020-02-04 22:08
Change permission is now granted by default to current user and its database group or reference-manager group in case of creating a reference record. Permission lists in config or user preferences yet to be implemented.

**Comment by enmust** [comment] 2020-09-09 08:45
UI is ready.

Tables: 'specimen', 'doi' and 'selection' need permissions
![image](https://user-images.githubusercontent.com/14908993/92576032-b17a8d80-f291-11ea-974b-4c30b0b88617.png)

On hold because of #429

**Comment by enmust** [comment] 2021-01-11 12:09
Seems to be duplicate of #574

**Closed by enmust** 2021-01-11 12:09 UTC
Labels: Difficulty: Medium, Priority: Medium, Source: API, Status: On Hold
